TimetableArranger/TimetableArranger.Web/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimetableArranger.BLL.Interfaces;
using TimetableArranger.Web.Models;
using TimetableArranger.Web.Infrastructure;

namespace TimetableArranger.Web.Controllers
{
    public class GroupController : Controller
    {
        //
        // GET: /Group/
        IGroupService groupService;

        public GroupController(IGroupService _groupService)
        {
            this.groupService = _groupService;
        }

        /// <summary>
        /// Wyświetlenie formularza dodawania grupy
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult Create()
        {
            GroupModel model = new GroupModel();
            model.Load(groupService.GetAll().ToList());
            return View(model);
        }

        /// <summary>
        /// Obsługa requestu dodania grupy
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [Authorize]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create(GroupModel model)
        {
            if (ModelState.IsValid)
            {
                if (groupService.Add(model.ParseToEntity()))
                    return RedirectToAction("Index", "Arranger");
                else
                    ModelState.AddModelError("", StaticStrings.ModelErrorMsgs.GroupSaveFail);
            }
            return View(model);
        }
    }
}

TimetableArranger/TimetableArranger.Web/Controllers/TutorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimetableArranger.BLL.Interfaces;
using TimetableArranger.Web.Models;
using TimetableArranger.DAL.Entities;
using TimetableArranger.Web.Infrastructure;

namespace TimetableArranger.Web.Controllers
{
    public class TutorController : Controller
    {
        //
        // GET: /Tutor/

        ITutorService tutorService;

        public TutorController(ITutorService _tutorService)
        {
            this.tutorService = _tutorService;
        }

        /// <summary>
        /// Wyświetlenie formularza dodawania nowego prowadzącego
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult Create()
        {
            TutorCreateModel model = new TutorCreateModel();
            model.Load(tutorService.GetAvailableTutorTitles(), tutorService.GetAll().ToList());
            return View(model);
        }

        /// <summary>
        /// Obsługa requestu dodania prowadzącego
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [Authorize]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create(TutorCreateModel model)
        {
            if (ModelState.IsValid)
            {
                if(tutorService.Add(model.ParseToEntity()))
                    return RedirectToAction("Create","Classroom");
                else
                    ModelState.AddModelError("",StaticStrings.ModelErrorMsgs.TutorSaveFail);
            }
            model.Load(tutorService.GetAvailableTutorTitles(), tutorService.GetAll().ToList());
            return View(model);
        }

    }
}

TimetableArranger/TimetableArranger.Web/Views/Group/Create.cshtml
@model TimetableArranger.Web.Models.GroupModel

@{
    ViewBag.Title = "Create";
    ViewBag.CssFilename = "style-group";
}
<div class="kreska">
<div id="ciemn"></div>
<div id="jasn"></div>
<div id="logo">
  <p><b style="font-weight:900">DASHBOARD</b></br>
  </p>
  <p style="font-size:11px">Kreator układania planu</p>
</div></div>
<div id="pole">
<div class="napisy" >@Html.ActionLink("PROWADZĄCY", "Create", "Tutor")</div>
<div class="napisy">@Html.ActionLink("SALE","Create","Classroom")</div>
<div class="napisy">@Html.ActionLink("PRZEDMIOT","Create","Course")</div>
<div class="napisy">@Html.ActionLink("GRUPY","Create","Group")</div>
    <div class="napisy" style="margin-left:90px">LISTA DODANYCH GRUP</div>
<div id="pusta"></div>
<div  class="ramka">
<div class="nazwa">

</div><!--nazwa-->
<div >
<label>Pełna nazwa</label>
		@*<input type="text" id="login" name="nick" value="" />*@
        @Html.EditorFor(m=>m.GroupEdited.Name)
    <div class="komunikaty">@Html.ValidationMessageFor(m=>m.GroupEdited.Name)</div>
	  </div>
        
<div>
<label>Skrócona nazwa</label>
		@*<input type="text" id="haslo" name="nick" value="" />*@
        @Html.EditorFor(m=>m.GroupEdited.AbbreviatedName)
    <div class="komunikaty">@Html.ValidationMessageFor(m=>m.GroupEdited.AbbreviatedName)</div>
	  </div>
<div>
<label>Rok semestr</label>
        @*<input type="text" id="haslo" name="nick" value="" />*@
        @Html.EditorFor(m=>m.GroupEdited.Semester)
    <div class="komunikaty">@Html.ValidationMessageFor(m=>m.GroupEdited.Semester)</div>
	  </div>
<div>
<label>Liczba studentów</label>
		@*<input type="text" id="Text1" name="nick" value="">*@
        @Html.EditorFor(m=>m.GroupEdited.StudentsCount)
        <div class="komunikaty">@Html.ValidationMessageFor(m=>m.GroupEdited.StudentsCount)</div>
	  </div>
   
    

</div>
<div><button>dodaj grupę</button></div> 
    <div class="kreska2"></div>
    <div class="kreska3"></div>

    <div class="tabela">
        <table>
            <tr><td style="width:180px; color:#33BBBF; font-size:10px">Nazwa grupy</td><td style="width:60px; color:#33BBBF; font-size:10px">Skrót</td><td style="width:80px; color:#33BBBF; font-size:10px">Rok Semestr</td><td style="width:115px; color:#33BBBF; font-size:10px">Liczba studentów</td><td style="width:100px; color:#33BBBF; font-size:10px">Modyfikacje</td></tr>
            @foreach (var gvModel in Model.GroupsList)
            {
            <tr><td>@gvModel.Name</td><td>@gvModel.AbbreviatedName</td><td>@gvModel.Semester</td><td>@gvModel.StudentsCount</td><td><a href=""><img border="none" src="@Url.Content("~/Content/images/index_14.gif")"></a><a href=""><img border="none" src="@Url.Content("~/Content/images/index_15.gif")"></a><a href=""><img border="none" src="@Url.Content("~/Content/images/index_16.gif")"></a><a href=""><img border="none" src="@Url.Content("~/Content/images/index_17.gif")"></a></td></tr>
            }
        </table>
    </div>