przykladMVC/ZespolowyTest/MvcApplication1/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL.Interfaces;

namespace MvcApplication1.Controllers
{
    public class AjaxController : Controller
    {
        IShopService shopService;

        public AjaxController(IShopService _shopService)
        {
            this.shopService = _shopService;
        }
        
        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult WywolanieAjaksowe(string parametr)
        {
            int liczbaProduktow = shopService.GetDzialyCountProducts(parametr);
            
            return new JsonResult(){Data=new {poleZwrocone=liczbaProduktow},JsonRequestBehavior=JsonRequestBehavior.AllowGet};
        }

    }
}

przykladMVC/ZespolowyTest/MvcApplication1/Controllers/DzialyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication1.Models;
using BLL.Interfaces;

namespace MvcApplication1.Controllers
{
    public class DzialyController : Controller
    {
        //
        // GET: /Dzialy/
        IShopService shopService;

        public DzialyController(IShopService _shopService)
        {
            this.shopService = _shopService;
        }
        
        public ActionResult Index()
        {
            DzialyModel model = new DzialyModel(shopService.GetDzialy());
            return View(model);
        }

    }
}

przykladMVC/ZespolowyTest/MvcApplication1/Views/Dzialy/Index.cshtml
@model MvcApplication1.Models.DzialyModel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<ul>
@foreach (string nazwa in Model.NazwyDzialow)
{
    <li><p>@nazwa</p><button class="ajaksowy">Wywołanie ajaksowe dla: @nazwa</button></li>
}
</ul>

<script type="text/javascript">
    $(document).ready(function () {
        $('.ajaksowy').click(function () {
            var tresc_li = $(this).parent().find('p').html();
            $.ajax('@Url.Action("WywolanieAjaksowe","Ajax")', {
                data:{parametr: tresc_li},
                success: function (data) {
                    alert('W tym dziale jest ' + data.poleZwrocone + ' produktów.');
                }
            });
        });
    });
</script>