TimetableArranger/TimetableArranger.Web/Controllers/ArrangerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimetableArranger.BLL.Interfaces;
using TimetableArranger.Web.Models;
using System.Web.Helpers;
using TimetableArranger.DAL.Entities;

namespace TimetableArranger.Web.Controllers
{
    public class ArrangerController : Controller
    {
        //
        // GET: /Arranger/
        ITimeTableArrangerService timetableSrv;
        ICourseService courseService;

        public ArrangerController(ITimeTableArrangerService _timetableSrv, ICourseService _courseService)
        {
            this.timetableSrv = _timetableSrv;
            this.courseService = _courseService;
        }

        [Authorize]
        public ActionResult Index()
        {
            ArrangerModel model = new ArrangerModel();
            model.Load(timetableSrv.GetUnassignedCourseItems());
            return View("My",model);
        }

        [Authorize]
        public JsonResult SaveCourse(int courseid, int day, TimeSpan time)
        {
            ZAJECIA course = courseService.GetById(courseid);
            if(course!=null)
            {
                course.godzina = time;
                course.dzien = day;
                courseService.Update(course);
            }
            return Json(true,JsonRequestBehavior.AllowGet);
        }

    }
}

TimetableArranger/TimetableArranger.Web/Views/Shared/LoginLogoutPartial.cshtml
@using TimetableArranger.Web.Infrastructure

@if(CookieHelper.IsLogged())
{
   <div class="gorneprawe">@Html.ActionLink(CookieHelper.GetUsername(),"Logout","Account")<img border="none" src="../Content/images/przycisk.png"></div>
    <div class="gorneprawe"><img border="none" src="images/index_07.gif"></div>
}
else
{
     <div class="gorneprawe">@Html.ActionLink("logowanie","Login","Account")<img border="none" src="images/przycisk.png"></div>    
}

TimetableArranger/TimetableArranger.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
<link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.3/jquery.min.js"></script>
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<title>@ViewBag.Title</title>
@*<link href="@Url.Content("~/Content/style.css")" rel="stylesheet" type="text/css" />*@
@if (ViewBag.CssFilename != null)
{
<link href="@Url.Content(string.Format("~/Content/{0}.css", ViewBag.CssFileName))" rel="stylesheet" type="text/css" />
}
@RenderSection("Headers",false)
</head>
<body>

<div id="calosc">


<div id="menugorne">
@Html.Partial("LoginLogoutPartial")
<div id="mengorne">
<div class="gorne"><a href="@Url.Action("Create","Course")"><img border="none" src="@Url.Content("~/Content/images/index_21.gif")">
Kreator</a></div>
<div class="ciemna"> </div>
<div class="jasna"> </div>
<div class="gorne"><a href="@Url.Action("Index","Arranger")"><img border="none" src="@Url.Content("~/Content/images/index_22.gif")"> Aranżer</a>
</div>
<div class="ciemna"></div>
<div class="jasna"></div>
<div class="gorne"><a href=""><img border="none" src="@Url.Content("~/Content/images/index_23.gif")"> Menadżer</a></div>
</div>
</div>



<div>
@RenderBody()
</div>
<div class="copyright">Copyright 2013 Grupa TM WZIM SGGW</div>


    </div>
</body>
</html>